<?php

namespace AppBundle\Repository;

/**
 * PointSortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointSortieRepository extends \Doctrine\ORM\EntityRepository
{
}
