<?php

namespace AppBundle\Repository;

/**
 * PositionEntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PositionEntreeRepository extends \Doctrine\ORM\EntityRepository
{
}
